name: ItemFinder
main: net.azisaba.itemFinder.ItemFinder
version: 2.0.0
api-version: 1.15
depend:
  - StorageBox
softdepend:
  - WorldEdit
commands:
  itemfinder:
    permission: itemfinder.command
permissions:
  itemfinder.notify:
    default: op
