name: ItemFinder
main: net.azisaba.itemFinder.ItemFinder
version: 1.1.3
api-version: 1.15
softdepend:
  - WorldEdit
commands:
  itemfinder:
    permission: itemfinder.command
permissions:
  itemfinder.notify:
    default: op
